// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Infrastructure.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251122163107_UpdateUser")]
    partial class UpdateUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Badge", b =>
                {
                    b.Property<int>("IdBadge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_badge");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBadge"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("icon_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name_badge");

                    b.HasKey("IdBadge");

                    b.ToTable("badge");
                });

            modelBuilder.Entity("backend.Models.BlockedUser", b =>
                {
                    b.Property<int>("IdUserBlocker")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_blocker");

                    b.Property<int>("IdUserBlocked")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_blocked");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("IdUserBlocker", "IdUserBlocked");

                    b.HasIndex("IdUserBlocked");

                    b.ToTable("blocked_users");
                });

            modelBuilder.Entity("backend.Models.Chat", b =>
                {
                    b.Property<int>("IdChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_chat");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdChat"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("IdTrip")
                        .HasColumnType("integer")
                        .HasColumnName("id_trip");

                    b.Property<bool>("IsGroupChat")
                        .HasColumnType("boolean")
                        .HasColumnName("is_group_chat");

                    b.HasKey("IdChat");

                    b.HasIndex("IdTrip");

                    b.ToTable("chat");
                });

            modelBuilder.Entity("backend.Models.Favourite", b =>
                {
                    b.Property<int>("IdFavourite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_favourite");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFavourite"));

                    b.Property<int?>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<int?>("IdUserFavourite")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_favourite");

                    b.HasKey("IdFavourite");

                    b.HasIndex("IdUser");

                    b.HasIndex("IdUserFavourite");

                    b.ToTable("favourite");
                });

            modelBuilder.Entity("backend.Models.Language", b =>
                {
                    b.Property<int>("IdLanguage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_language");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLanguage"));

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("language_name");

                    b.HasKey("IdLanguage");

                    b.ToTable("language");
                });

            modelBuilder.Entity("backend.Models.Message", b =>
                {
                    b.Property<int>("IdMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_message");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMessage"));

                    b.Property<int>("IdChat")
                        .HasColumnType("integer");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_chat");

                    b.Property<int?>("IdUserSender")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_sender");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("media_url");

                    b.Property<string>("Text")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("IdMessage");

                    b.HasIndex("IdChat");

                    b.HasIndex("IdUserSender");

                    b.ToTable("message");
                });

            modelBuilder.Entity("backend.Models.Notification", b =>
                {
                    b.Property<int>("IdNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_notification");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotification"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("IdMessage")
                        .HasColumnType("integer")
                        .HasColumnName("id_message");

                    b.Property<int?>("IdReview")
                        .HasColumnType("integer")
                        .HasColumnName("id_review");

                    b.Property<int?>("IdTripInvitation")
                        .HasColumnType("integer")
                        .HasColumnName("id_trip_invitation");

                    b.Property<int?>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<int?>("ReviewIdReview")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("IdNotification");

                    b.HasIndex("IdMessage");

                    b.HasIndex("IdTripInvitation")
                        .IsUnique();

                    b.HasIndex("IdUser");

                    b.HasIndex("ReviewIdReview");

                    b.ToTable("notification");
                });

            modelBuilder.Entity("backend.Models.Review", b =>
                {
                    b.Property<int>("IdReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_review");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReview"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("IdUserReviewed")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_reviewed");

                    b.Property<int?>("IdUserReviewer")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_reviewer");

                    b.Property<bool>("IsReported")
                        .HasColumnType("boolean")
                        .HasColumnName("is_reported");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("text");

                    b.HasKey("IdReview");

                    b.HasIndex("IdUserReviewed");

                    b.HasIndex("IdUserReviewer");

                    b.ToTable("review");
                });

            modelBuilder.Entity("backend.Models.SearchFilter", b =>
                {
                    b.Property<int>("IdSearchFilter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_search_filter");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSearchFilter"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("criteria");

                    b.Property<int?>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name_search_filter");

                    b.HasKey("IdSearchFilter");

                    b.HasIndex("IdUser");

                    b.ToTable("search_filter");
                });

            modelBuilder.Entity("backend.Models.Trip", b =>
                {
                    b.Property<int>("IdTrip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_trip");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTrip"));

                    b.Property<decimal?>("BudgetAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("budget_amount");

                    b.Property<string>("BudgetCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("budget_currency");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("destination");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsReported")
                        .HasColumnType("boolean")
                        .HasColumnName("is_reported");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("title");

                    b.Property<string>("TravelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("travel_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdTrip");

                    b.ToTable("trip");
                });

            modelBuilder.Entity("backend.Models.TripInvitation", b =>
                {
                    b.Property<int>("IdTripInvitation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_trip_invitation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTripInvitation"));

                    b.Property<int?>("IdUserInvited")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_invited");

                    b.Property<int?>("IdUserInviting")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_inviting");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TripId")
                        .HasColumnType("integer")
                        .HasColumnName("id_trip");

                    b.HasKey("IdTripInvitation");

                    b.HasIndex("IdUserInvited");

                    b.HasIndex("IdUserInviting");

                    b.HasIndex("TripId");

                    b.ToTable("trip_invitation");
                });

            modelBuilder.Entity("backend.Models.TripPhoto", b =>
                {
                    b.Property<int>("IdTripPhoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_trip_photo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTripPhoto"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("IdTrip")
                        .HasColumnType("integer")
                        .HasColumnName("id_trip");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("photo_path");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("integer")
                        .HasColumnName("uploaded_by");

                    b.HasKey("IdTripPhoto");

                    b.HasIndex("IdTrip");

                    b.HasIndex("UploadedBy");

                    b.ToTable("trip_photo");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUser"));

                    b.Property<string>("AlcoholPreference")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("alcohol_preference");

                    b.Property<string>("BackgroundPhotoPath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("background_photo_path");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("display_name");

                    b.Property<string>("DrivingLicenseType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("driving_license_type");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_blocked");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PersonalityType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("personality_type");

                    b.Property<string>("ProfilePhotoPath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("profile_photo_path");

                    b.Property<string>("Pronouns")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pronouns");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("SmokingPreference")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("smoking_preference");

                    b.Property<string>("SystemLanguage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("system_language");

                    b.Property<bool>("ToBeDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("to_be_deleted");

                    b.Property<string>("TravelExperience")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("travel_experience");

                    b.Property<string>("TravelStyle")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("travel_style");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("IdUser");

                    b.ToTable("user");
                });

            modelBuilder.Entity("backend.Models.UserBadge", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<int>("IdBadge")
                        .HasColumnType("integer")
                        .HasColumnName("id_badge");

                    b.HasKey("IdUser", "IdBadge");

                    b.HasIndex("IdBadge");

                    b.ToTable("user_badge");
                });

            modelBuilder.Entity("backend.Models.UserChat", b =>
                {
                    b.Property<int>("IdChat")
                        .HasColumnType("integer")
                        .HasColumnName("id_chat");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.HasKey("IdChat", "IdUser");

                    b.HasIndex("IdUser");

                    b.ToTable("user_chat");
                });

            modelBuilder.Entity("backend.Models.UserLanguage", b =>
                {
                    b.Property<int>("IdLanguage")
                        .HasColumnType("integer")
                        .HasColumnName("id_language");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.HasKey("IdLanguage", "IdUser");

                    b.HasIndex("IdUser");

                    b.ToTable("user_language");
                });

            modelBuilder.Entity("backend.Models.BlockedUser", b =>
                {
                    b.HasOne("backend.Models.User", "Blocked")
                        .WithMany("UsersBlockingThisUser")
                        .HasForeignKey("IdUserBlocked")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "Blocker")
                        .WithMany("BlockedUsers")
                        .HasForeignKey("IdUserBlocker")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blocked");

                    b.Navigation("Blocker");
                });

            modelBuilder.Entity("backend.Models.Chat", b =>
                {
                    b.HasOne("backend.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("IdTrip");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("backend.Models.Favourite", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany("FavouritesGiven")
                        .HasForeignKey("IdUser");

                    b.HasOne("backend.Models.User", "FavouriteUser")
                        .WithMany("FavouritesReceived")
                        .HasForeignKey("IdUserFavourite");

                    b.Navigation("FavouriteUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Message", b =>
                {
                    b.HasOne("backend.Models.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("IdChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("IdUserSender");

                    b.Navigation("Chat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("backend.Models.Notification", b =>
                {
                    b.HasOne("backend.Models.Message", "Message")
                        .WithMany("Notifications")
                        .HasForeignKey("IdMessage")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.TripInvitation", "TripInvitation")
                        .WithOne("Notification")
                        .HasForeignKey("backend.Models.Notification", "IdTripInvitation");

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("IdUser");

                    b.HasOne("backend.Models.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewIdReview");

                    b.Navigation("Message");

                    b.Navigation("Review");

                    b.Navigation("TripInvitation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Review", b =>
                {
                    b.HasOne("backend.Models.User", "ReviewedUser")
                        .WithMany("ReviewsReceived")
                        .HasForeignKey("IdUserReviewed");

                    b.HasOne("backend.Models.User", "Reviewer")
                        .WithMany("ReviewsWritten")
                        .HasForeignKey("IdUserReviewer");

                    b.Navigation("ReviewedUser");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("backend.Models.SearchFilter", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany("SearchFilters")
                        .HasForeignKey("IdUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.TripInvitation", b =>
                {
                    b.HasOne("backend.Models.User", "InvitedUser")
                        .WithMany("TripInvitationsReceived")
                        .HasForeignKey("IdUserInvited");

                    b.HasOne("backend.Models.User", "InvitingUser")
                        .WithMany("TripInvitationsSent")
                        .HasForeignKey("IdUserInviting");

                    b.HasOne("backend.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvitedUser");

                    b.Navigation("InvitingUser");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("backend.Models.TripPhoto", b =>
                {
                    b.HasOne("backend.Models.Trip", "Trip")
                        .WithMany("Photos")
                        .HasForeignKey("IdTrip")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "UploadedByUser")
                        .WithMany("TripPhotosUploaded")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("backend.Models.UserBadge", b =>
                {
                    b.HasOne("backend.Models.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("IdBadge")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("UserBadges")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.UserChat", b =>
                {
                    b.HasOne("backend.Models.Chat", "Chat")
                        .WithMany("UserChats")
                        .HasForeignKey("IdChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("UserChats")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.UserLanguage", b =>
                {
                    b.HasOne("backend.Models.Language", "Language")
                        .WithMany("UserLanguages")
                        .HasForeignKey("IdLanguage")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("UserLanguages")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("backend.Models.Chat", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("UserChats");
                });

            modelBuilder.Entity("backend.Models.Language", b =>
                {
                    b.Navigation("UserLanguages");
                });

            modelBuilder.Entity("backend.Models.Message", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("backend.Models.Trip", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("backend.Models.TripInvitation", b =>
                {
                    b.Navigation("Notification");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("BlockedUsers");

                    b.Navigation("FavouritesGiven");

                    b.Navigation("FavouritesReceived");

                    b.Navigation("Notifications");

                    b.Navigation("ReviewsReceived");

                    b.Navigation("ReviewsWritten");

                    b.Navigation("SearchFilters");

                    b.Navigation("TripInvitationsReceived");

                    b.Navigation("TripInvitationsSent");

                    b.Navigation("TripPhotosUploaded");

                    b.Navigation("UserBadges");

                    b.Navigation("UserChats");

                    b.Navigation("UserLanguages");

                    b.Navigation("UsersBlockingThisUser");
                });
#pragma warning restore 612, 618
        }
    }
}
