// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Infrastructure.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260426191623_BlockedUserChanges")]
    partial class BlockedUserChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.CategoriesOptions.Models.AlcoholPreferenceOption", b =>
                {
                    b.Property<int>("IdAlcoholPreference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_alcohol_preference");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAlcoholPreference"));

                    b.Property<string>("AlcoholPreferenceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alcohol_preference_name");

                    b.HasKey("IdAlcoholPreference");

                    b.ToTable("alcohol_preference");

                    b.HasData(
                        new
                        {
                            IdAlcoholPreference = 1,
                            AlcoholPreferenceName = "Nie piję i nie przeszkadza mi"
                        },
                        new
                        {
                            IdAlcoholPreference = 2,
                            AlcoholPreferenceName = "Piję okazjonalnie"
                        },
                        new
                        {
                            IdAlcoholPreference = 3,
                            AlcoholPreferenceName = "Piję regularnie"
                        },
                        new
                        {
                            IdAlcoholPreference = 4,
                            AlcoholPreferenceName = "Nie toleruję"
                        });
                });

            modelBuilder.Entity("backend.CategoriesOptions.Models.DrivingLicenseOption", b =>
                {
                    b.Property<int>("IdDrivingLicense")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_driving_license");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDrivingLicense"));

                    b.Property<string>("DrivingLicenseName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("driving_license_name");

                    b.HasKey("IdDrivingLicense");

                    b.ToTable("driving_license");

                    b.HasData(
                        new
                        {
                            IdDrivingLicense = 1,
                            DrivingLicenseName = "Posiadam międzynarodowe"
                        },
                        new
                        {
                            IdDrivingLicense = 2,
                            DrivingLicenseName = "Nie posiadam"
                        },
                        new
                        {
                            IdDrivingLicense = 3,
                            DrivingLicenseName = "Inne"
                        });
                });

            modelBuilder.Entity("backend.CategoriesOptions.Models.GenderOption", b =>
                {
                    b.Property<int>("IdGender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_gender");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdGender"));

                    b.Property<string>("GenderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender_name");

                    b.HasKey("IdGender");

                    b.ToTable("gender");

                    b.HasData(
                        new
                        {
                            IdGender = 1,
                            GenderName = "Mężczyzna"
                        },
                        new
                        {
                            IdGender = 2,
                            GenderName = "Kobieta"
                        },
                        new
                        {
                            IdGender = 3,
                            GenderName = "Niebinarny"
                        },
                        new
                        {
                            IdGender = 4,
                            GenderName = "Inne"
                        });
                });

            modelBuilder.Entity("backend.CategoriesOptions.Models.PersonalityTypeOption", b =>
                {
                    b.Property<int>("IdPersonalityType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_personality_type");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPersonalityType"));

                    b.Property<string>("PersonalityTypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("personality_type_name");

                    b.HasKey("IdPersonalityType");

                    b.ToTable("personality_type");

                    b.HasData(
                        new
                        {
                            IdPersonalityType = 1,
                            PersonalityTypeName = "Introwertyk"
                        },
                        new
                        {
                            IdPersonalityType = 2,
                            PersonalityTypeName = "Ekstrawertyk"
                        },
                        new
                        {
                            IdPersonalityType = 3,
                            PersonalityTypeName = "Ambiwertyk"
                        });
                });

            modelBuilder.Entity("backend.CategoriesOptions.Models.PronounOption", b =>
                {
                    b.Property<int>("IdPronoun")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pronoun");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPronoun"));

                    b.Property<string>("PronounName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pronoun_name");

                    b.HasKey("IdPronoun");

                    b.ToTable("pronoun");

                    b.HasData(
                        new
                        {
                            IdPronoun = 1,
                            PronounName = "On/Jego"
                        },
                        new
                        {
                            IdPronoun = 2,
                            PronounName = "Ona/Jej"
                        },
                        new
                        {
                            IdPronoun = 3,
                            PronounName = "Oni/Ich"
                        });
                });

            modelBuilder.Entity("backend.CategoriesOptions.Models.SmokingPreferenceOption", b =>
                {
                    b.Property<int>("IdSmokingPreference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_smoking_preference");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSmokingPreference"));

                    b.Property<string>("SmokingPreferenceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("smoking_preference_name");

                    b.HasKey("IdSmokingPreference");

                    b.ToTable("smoking_preference");

                    b.HasData(
                        new
                        {
                            IdSmokingPreference = 1,
                            SmokingPreferenceName = "Nie palę i nie przeszkadza mi"
                        },
                        new
                        {
                            IdSmokingPreference = 2,
                            SmokingPreferenceName = "Palę okazjonalnie"
                        },
                        new
                        {
                            IdSmokingPreference = 3,
                            SmokingPreferenceName = "Palę"
                        },
                        new
                        {
                            IdSmokingPreference = 4,
                            SmokingPreferenceName = "Nie toleruję"
                        });
                });

            modelBuilder.Entity("backend.CategoriesOptions.Models.TravelExperienceOption", b =>
                {
                    b.Property<int>("IdTravelExperience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_travel_experience");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTravelExperience"));

                    b.Property<string>("TravelExperienceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("travel_experience_name");

                    b.HasKey("IdTravelExperience");

                    b.ToTable("travel_experience");

                    b.HasData(
                        new
                        {
                            IdTravelExperience = 1,
                            TravelExperienceName = "Początkujący"
                        },
                        new
                        {
                            IdTravelExperience = 2,
                            TravelExperienceName = "Średniozaawansowany"
                        },
                        new
                        {
                            IdTravelExperience = 3,
                            TravelExperienceName = "Zaawansowany"
                        },
                        new
                        {
                            IdTravelExperience = 4,
                            TravelExperienceName = "Backpacker"
                        });
                });

            modelBuilder.Entity("backend.Interest.Interest", b =>
                {
                    b.Property<int>("IdInterest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_interest");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInterest"));

                    b.Property<string>("InterestName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("interest_name");

                    b.HasKey("IdInterest");

                    b.ToTable("interest");
                });

            modelBuilder.Entity("backend.Interest.UserInterest", b =>
                {
                    b.Property<int>("IdInterest")
                        .HasColumnType("integer")
                        .HasColumnName("id_interest");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.HasKey("IdInterest", "IdUser");

                    b.HasIndex("IdUser");

                    b.ToTable("user_interest");
                });

            modelBuilder.Entity("backend.Language.Language", b =>
                {
                    b.Property<int>("IdLanguage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_language");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLanguage"));

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("language_name");

                    b.HasKey("IdLanguage");

                    b.ToTable("language");
                });

            modelBuilder.Entity("backend.Language.UserLanguage", b =>
                {
                    b.Property<int>("IdLanguage")
                        .HasColumnType("integer")
                        .HasColumnName("id_language");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.HasKey("IdLanguage", "IdUser");

                    b.HasIndex("IdUser");

                    b.ToTable("user_language");
                });

            modelBuilder.Entity("backend.Models.Badge", b =>
                {
                    b.Property<int>("IdBadge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_badge");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBadge"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("icon_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name_badge");

                    b.HasKey("IdBadge");

                    b.ToTable("badge");
                });

            modelBuilder.Entity("backend.Models.Chat", b =>
                {
                    b.Property<int>("IdChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_chat");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdChat"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("IdTrip")
                        .HasColumnType("integer")
                        .HasColumnName("id_trip");

                    b.Property<bool>("IsGroupChat")
                        .HasColumnType("boolean")
                        .HasColumnName("is_group_chat");

                    b.HasKey("IdChat");

                    b.HasIndex("IdTrip");

                    b.ToTable("chat");
                });

            modelBuilder.Entity("backend.Models.Message", b =>
                {
                    b.Property<int>("IdMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_message");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMessage"));

                    b.Property<int>("IdChat")
                        .HasColumnType("integer");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_chat");

                    b.Property<int?>("IdUserSender")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_sender");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("media_url");

                    b.Property<string>("Text")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("IdMessage");

                    b.HasIndex("IdChat");

                    b.HasIndex("IdUserSender");

                    b.ToTable("message");
                });

            modelBuilder.Entity("backend.Models.Review", b =>
                {
                    b.Property<int>("IdReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_review");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReview"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("IdUserReviewed")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_reviewed");

                    b.Property<int?>("IdUserReviewer")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_reviewer");

                    b.Property<bool>("IsReported")
                        .HasColumnType("boolean")
                        .HasColumnName("is_reported");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("text");

                    b.HasKey("IdReview");

                    b.HasIndex("IdUserReviewed");

                    b.HasIndex("IdUserReviewer");

                    b.ToTable("review");
                });

            modelBuilder.Entity("backend.Models.SearchFilter", b =>
                {
                    b.Property<int>("IdSearchFilter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_search_filter");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSearchFilter"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("criteria");

                    b.Property<int?>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name_search_filter");

                    b.HasKey("IdSearchFilter");

                    b.HasIndex("IdUser");

                    b.ToTable("search_filter");
                });

            modelBuilder.Entity("backend.Models.TripInvitation", b =>
                {
                    b.Property<int>("IdTripInvitation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_trip_invitation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTripInvitation"));

                    b.Property<int?>("IdUserInvited")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_invited");

                    b.Property<int?>("IdUserInviting")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_inviting");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TripId")
                        .HasColumnType("integer")
                        .HasColumnName("id_trip");

                    b.HasKey("IdTripInvitation");

                    b.HasIndex("IdUserInvited");

                    b.HasIndex("IdUserInviting");

                    b.HasIndex("TripId");

                    b.ToTable("trip_invitation");
                });

            modelBuilder.Entity("backend.Models.TripPhoto", b =>
                {
                    b.Property<int>("IdTripPhoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_trip_photo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTripPhoto"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("IdTrip")
                        .HasColumnType("integer")
                        .HasColumnName("id_trip");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("photo_path");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("integer")
                        .HasColumnName("uploaded_by");

                    b.HasKey("IdTripPhoto");

                    b.HasIndex("IdTrip");

                    b.HasIndex("UploadedBy");

                    b.ToTable("trip_photo");
                });

            modelBuilder.Entity("backend.Models.UserBadge", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<int>("IdBadge")
                        .HasColumnType("integer")
                        .HasColumnName("id_badge");

                    b.HasKey("IdUser", "IdBadge");

                    b.HasIndex("IdBadge");

                    b.ToTable("user_badge");
                });

            modelBuilder.Entity("backend.Models.UserChat", b =>
                {
                    b.Property<int>("IdChat")
                        .HasColumnType("integer")
                        .HasColumnName("id_chat");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.HasKey("IdChat", "IdUser");

                    b.HasIndex("IdUser");

                    b.ToTable("user_chat");
                });

            modelBuilder.Entity("backend.Notification.Notification", b =>
                {
                    b.Property<int>("IdNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_notification");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotification"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("IdMessage")
                        .HasColumnType("integer")
                        .HasColumnName("id_message");

                    b.Property<int?>("IdReview")
                        .HasColumnType("integer")
                        .HasColumnName("id_review");

                    b.Property<int?>("IdTripInvitation")
                        .HasColumnType("integer")
                        .HasColumnName("id_trip_invitation");

                    b.Property<int?>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<int?>("ReviewIdReview")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("IdNotification");

                    b.HasIndex("IdMessage");

                    b.HasIndex("IdTripInvitation")
                        .IsUnique();

                    b.HasIndex("IdUser");

                    b.HasIndex("ReviewIdReview");

                    b.ToTable("notification");
                });

            modelBuilder.Entity("backend.TransportMode.TransportMode", b =>
                {
                    b.Property<int>("IdTransportMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_transport_mode");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTransportMode"));

                    b.Property<string>("TransportModeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transport_mode_name");

                    b.HasKey("IdTransportMode");

                    b.ToTable("transport_mode");

                    b.HasData(
                        new
                        {
                            IdTransportMode = 1,
                            TransportModeName = "Samochód"
                        },
                        new
                        {
                            IdTransportMode = 2,
                            TransportModeName = "Samolot"
                        },
                        new
                        {
                            IdTransportMode = 3,
                            TransportModeName = "Pociąg"
                        },
                        new
                        {
                            IdTransportMode = 4,
                            TransportModeName = "Autobus"
                        },
                        new
                        {
                            IdTransportMode = 5,
                            TransportModeName = "Rower"
                        },
                        new
                        {
                            IdTransportMode = 6,
                            TransportModeName = "Motor"
                        },
                        new
                        {
                            IdTransportMode = 7,
                            TransportModeName = "Prom"
                        });
                });

            modelBuilder.Entity("backend.TransportMode.UserTransportMode", b =>
                {
                    b.Property<int>("IdTransportMode")
                        .HasColumnType("integer")
                        .HasColumnName("id_transport_mode");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.HasKey("IdTransportMode", "IdUser");

                    b.HasIndex("IdUser");

                    b.ToTable("user_transport_mode");
                });

            modelBuilder.Entity("backend.TravelStyle.TravelStyle", b =>
                {
                    b.Property<int>("IdTravelStyle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_travel_style");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTravelStyle"));

                    b.Property<string>("TravelStyleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("travel_style_name");

                    b.HasKey("IdTravelStyle");

                    b.ToTable("travel_style");

                    b.HasData(
                        new
                        {
                            IdTravelStyle = 1,
                            TravelStyleName = "Spontaniczny"
                        },
                        new
                        {
                            IdTravelStyle = 2,
                            TravelStyleName = "Trochę zaplanowany"
                        },
                        new
                        {
                            IdTravelStyle = 3,
                            TravelStyleName = "Szczegółowo zaplanowany"
                        },
                        new
                        {
                            IdTravelStyle = 4,
                            TravelStyleName = "All-inclusive"
                        },
                        new
                        {
                            IdTravelStyle = 5,
                            TravelStyleName = "City break"
                        },
                        new
                        {
                            IdTravelStyle = 6,
                            TravelStyleName = "Road trip"
                        },
                        new
                        {
                            IdTravelStyle = 7,
                            TravelStyleName = "Wakacje z biurem podróży"
                        },
                        new
                        {
                            IdTravelStyle = 8,
                            TravelStyleName = "Podróże ekstremalne"
                        },
                        new
                        {
                            IdTravelStyle = 9,
                            TravelStyleName = "Slow travel"
                        },
                        new
                        {
                            IdTravelStyle = 10,
                            TravelStyleName = "Backpacking"
                        });
                });

            modelBuilder.Entity("backend.TravelStyle.UserTravelStyle", b =>
                {
                    b.Property<int>("IdTravelStyle")
                        .HasColumnType("integer")
                        .HasColumnName("id_travel_style");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.HasKey("IdTravelStyle", "IdUser");

                    b.HasIndex("IdUser");

                    b.ToTable("user_travel_style");
                });

            modelBuilder.Entity("backend.Trip.Trip", b =>
                {
                    b.Property<int>("IdTrip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_trip");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTrip"));

                    b.Property<decimal>("BudgetAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("budget_amount");

                    b.Property<string>("BudgetCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("budget_currency");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("destination");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsReported")
                        .HasColumnType("boolean")
                        .HasColumnName("is_reported");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("title");

                    b.Property<string>("TravelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("travel_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdTrip");

                    b.ToTable("trip");
                });

            modelBuilder.Entity("backend.User.Models.BlockedUser", b =>
                {
                    b.Property<int>("IdBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_blocked");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBlocked"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("IdUserBlocked")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_blocked");

                    b.Property<int>("IdUserBlocker")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_blocker");

                    b.HasKey("IdBlocked");

                    b.HasIndex("IdUserBlocked");

                    b.HasIndex("IdUserBlocker");

                    b.ToTable("blocked_users");
                });

            modelBuilder.Entity("backend.User.Models.Favourite", b =>
                {
                    b.Property<int>("IdFavourite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_favourite");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFavourite"));

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<int>("IdUserFavourite")
                        .HasColumnType("integer")
                        .HasColumnName("id_user_favourite");

                    b.HasKey("IdFavourite");

                    b.HasIndex("IdUser");

                    b.HasIndex("IdUserFavourite");

                    b.ToTable("favourite");
                });

            modelBuilder.Entity("backend.User.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUser"));

                    b.Property<int?>("AlcoholPreferenceId")
                        .HasColumnType("integer")
                        .HasColumnName("alcohol_preference");

                    b.Property<string>("BackgroundPhotoPath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("background_photo_path");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("display_name");

                    b.Property<int?>("DrivingLicenseId")
                        .HasColumnType("integer")
                        .HasColumnName("driving_license_type");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<int>("EmailVerificationAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("email_verification_attempts");

                    b.Property<string>("EmailVerificationCodeHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email_verification_code_hash");

                    b.Property<DateTime?>("EmailVerificationExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verification_expires_at");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<int?>("GenderId")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_blocked");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<int?>("PersonalityTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("personality_type");

                    b.Property<string>("ProfilePhotoPath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("profile_photo_path");

                    b.Property<int?>("PronounsId")
                        .HasColumnType("integer")
                        .HasColumnName("pronouns");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<int?>("SmokingPreferenceId")
                        .HasColumnType("integer")
                        .HasColumnName("smoking_preference");

                    b.Property<bool>("ToBeDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("to_be_deleted");

                    b.Property<int?>("TravelExperienceId")
                        .HasColumnType("integer")
                        .HasColumnName("travel_experience");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("IdUser");

                    b.HasIndex("AlcoholPreferenceId");

                    b.HasIndex("DisplayName")
                        .HasDatabaseName("ix_user_displayname_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("DisplayName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("DisplayName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("DrivingLicenseId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GenderId");

                    b.HasIndex("PersonalityTypeId");

                    b.HasIndex("PronounsId");

                    b.HasIndex("SmokingPreferenceId");

                    b.HasIndex("TravelExperienceId");

                    b.HasIndex("Username")
                        .HasDatabaseName("ix_user_username_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Username"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Username"), new[] { "gin_trgm_ops" });

                    b.ToTable("user");
                });

            modelBuilder.Entity("backend.Interest.UserInterest", b =>
                {
                    b.HasOne("backend.Interest.Interest", "Interest")
                        .WithMany("UserInterests")
                        .HasForeignKey("IdInterest")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.User.Models.User", "User")
                        .WithMany("UserInterests")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Language.UserLanguage", b =>
                {
                    b.HasOne("backend.Language.Language", "Language")
                        .WithMany("UserLanguages")
                        .HasForeignKey("IdLanguage")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.User.Models.User", "User")
                        .WithMany("UserLanguages")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Chat", b =>
                {
                    b.HasOne("backend.Trip.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("IdTrip");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("backend.Models.Message", b =>
                {
                    b.HasOne("backend.Models.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("IdChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.User.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("IdUserSender");

                    b.Navigation("Chat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("backend.Models.Review", b =>
                {
                    b.HasOne("backend.User.Models.User", "ReviewedUser")
                        .WithMany("ReviewsReceived")
                        .HasForeignKey("IdUserReviewed");

                    b.HasOne("backend.User.Models.User", "Reviewer")
                        .WithMany("ReviewsWritten")
                        .HasForeignKey("IdUserReviewer");

                    b.Navigation("ReviewedUser");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("backend.Models.SearchFilter", b =>
                {
                    b.HasOne("backend.User.Models.User", "User")
                        .WithMany("SearchFilters")
                        .HasForeignKey("IdUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.TripInvitation", b =>
                {
                    b.HasOne("backend.User.Models.User", "InvitedUser")
                        .WithMany("TripInvitationsReceived")
                        .HasForeignKey("IdUserInvited");

                    b.HasOne("backend.User.Models.User", "InvitingUser")
                        .WithMany("TripInvitationsSent")
                        .HasForeignKey("IdUserInviting");

                    b.HasOne("backend.Trip.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvitedUser");

                    b.Navigation("InvitingUser");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("backend.Models.TripPhoto", b =>
                {
                    b.HasOne("backend.Trip.Trip", "Trip")
                        .WithMany("Photos")
                        .HasForeignKey("IdTrip")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.User.Models.User", "UploadedByUser")
                        .WithMany("TripPhotosUploaded")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("backend.Models.UserBadge", b =>
                {
                    b.HasOne("backend.Models.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("IdBadge")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.User.Models.User", "User")
                        .WithMany("UserBadges")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.UserChat", b =>
                {
                    b.HasOne("backend.Models.Chat", "Chat")
                        .WithMany("UserChats")
                        .HasForeignKey("IdChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.User.Models.User", "User")
                        .WithMany("UserChats")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Notification.Notification", b =>
                {
                    b.HasOne("backend.Models.Message", "Message")
                        .WithMany("Notifications")
                        .HasForeignKey("IdMessage")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.TripInvitation", "TripInvitation")
                        .WithOne("Notification")
                        .HasForeignKey("backend.Notification.Notification", "IdTripInvitation");

                    b.HasOne("backend.User.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("IdUser");

                    b.HasOne("backend.Models.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewIdReview");

                    b.Navigation("Message");

                    b.Navigation("Review");

                    b.Navigation("TripInvitation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.TransportMode.UserTransportMode", b =>
                {
                    b.HasOne("backend.TransportMode.TransportMode", "TransportMode")
                        .WithMany("UserTransportModes")
                        .HasForeignKey("IdTransportMode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.User.Models.User", "User")
                        .WithMany("UserTransportModes")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransportMode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.TravelStyle.UserTravelStyle", b =>
                {
                    b.HasOne("backend.TravelStyle.TravelStyle", "TravelStyle")
                        .WithMany("UserTravelStyles")
                        .HasForeignKey("IdTravelStyle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.User.Models.User", "User")
                        .WithMany("UserTravelStyles")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelStyle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.User.Models.BlockedUser", b =>
                {
                    b.HasOne("backend.User.Models.User", "Blocked")
                        .WithMany("BlockedUsers")
                        .HasForeignKey("IdUserBlocked")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.User.Models.User", "Blocker")
                        .WithMany("UsersBlockingThisUser")
                        .HasForeignKey("IdUserBlocker")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blocked");

                    b.Navigation("Blocker");
                });

            modelBuilder.Entity("backend.User.Models.Favourite", b =>
                {
                    b.HasOne("backend.User.Models.User", "User")
                        .WithMany("FavouritesGiven")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.User.Models.User", "FavouriteUser")
                        .WithMany("FavouritesReceived")
                        .HasForeignKey("IdUserFavourite")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FavouriteUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.User.Models.User", b =>
                {
                    b.HasOne("backend.CategoriesOptions.Models.AlcoholPreferenceOption", "AlcoholPreference")
                        .WithMany()
                        .HasForeignKey("AlcoholPreferenceId");

                    b.HasOne("backend.CategoriesOptions.Models.DrivingLicenseOption", "DrivingLicense")
                        .WithMany()
                        .HasForeignKey("DrivingLicenseId");

                    b.HasOne("backend.CategoriesOptions.Models.GenderOption", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId");

                    b.HasOne("backend.CategoriesOptions.Models.PersonalityTypeOption", "PersonalityType")
                        .WithMany()
                        .HasForeignKey("PersonalityTypeId");

                    b.HasOne("backend.CategoriesOptions.Models.PronounOption", "Pronouns")
                        .WithMany()
                        .HasForeignKey("PronounsId");

                    b.HasOne("backend.CategoriesOptions.Models.SmokingPreferenceOption", "SmokingPreference")
                        .WithMany()
                        .HasForeignKey("SmokingPreferenceId");

                    b.HasOne("backend.CategoriesOptions.Models.TravelExperienceOption", "TravelExperience")
                        .WithMany()
                        .HasForeignKey("TravelExperienceId");

                    b.Navigation("AlcoholPreference");

                    b.Navigation("DrivingLicense");

                    b.Navigation("Gender");

                    b.Navigation("PersonalityType");

                    b.Navigation("Pronouns");

                    b.Navigation("SmokingPreference");

                    b.Navigation("TravelExperience");
                });

            modelBuilder.Entity("backend.Interest.Interest", b =>
                {
                    b.Navigation("UserInterests");
                });

            modelBuilder.Entity("backend.Language.Language", b =>
                {
                    b.Navigation("UserLanguages");
                });

            modelBuilder.Entity("backend.Models.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("backend.Models.Chat", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("UserChats");
                });

            modelBuilder.Entity("backend.Models.Message", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("backend.Models.TripInvitation", b =>
                {
                    b.Navigation("Notification");
                });

            modelBuilder.Entity("backend.TransportMode.TransportMode", b =>
                {
                    b.Navigation("UserTransportModes");
                });

            modelBuilder.Entity("backend.TravelStyle.TravelStyle", b =>
                {
                    b.Navigation("UserTravelStyles");
                });

            modelBuilder.Entity("backend.Trip.Trip", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("backend.User.Models.User", b =>
                {
                    b.Navigation("BlockedUsers");

                    b.Navigation("FavouritesGiven");

                    b.Navigation("FavouritesReceived");

                    b.Navigation("Notifications");

                    b.Navigation("ReviewsReceived");

                    b.Navigation("ReviewsWritten");

                    b.Navigation("SearchFilters");

                    b.Navigation("TripInvitationsReceived");

                    b.Navigation("TripInvitationsSent");

                    b.Navigation("TripPhotosUploaded");

                    b.Navigation("UserBadges");

                    b.Navigation("UserChats");

                    b.Navigation("UserInterests");

                    b.Navigation("UserLanguages");

                    b.Navigation("UserTransportModes");

                    b.Navigation("UserTravelStyles");

                    b.Navigation("UsersBlockingThisUser");
                });
#pragma warning restore 612, 618
        }
    }
}
